### ISSUE TITLE
代码运行较长时间后中断

### ISSUE THREAD

**Issue by songwenhao123** [Linfeng-Tang/VIF-Benchmark#3]
你好，我运行代码后出现了代码运行很久后中断的问题，请问可以帮助解决吗？十分感谢
0%|                                                                                                                                                                                         | 0/12 [00:00<?, ?it/s]  0%|                                                                                                                                                                                         | 0/12 [12:29<?, ?it/s]
Traceback (most recent call last):
  File "CSF.py", line 60, in <module>
    is_RGB=opts.is_RGB
  File "CSF.py", line 36, in main
    generate(ir_path, vis_path, model_path_1, model_path_2, output_path=save_path)
  File "/home/wenhao/projects/VIF-Benchmark/CSF/generate.py", line 56, in generate
    vis_feas_output = sess.run(feas, feed_dict = FEED_DICT_VIS)
  File "/home/wenhao/installs/conda/envs/timer/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/wenhao/installs/conda/envs/timer/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/wenhao/installs/conda/envs/timer/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/home/wenhao/installs/conda/envs/timer/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/home/wenhao/installs/conda/envs/timer/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/wenhao/installs/conda/envs/timer/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
KeyboardInterrupt

**Comment by WenhaoSong-1512** [comment]
您好，我换了一张显卡后成功运行，可是生成的融合图像比较糟糕，请问是什么原因？以CSF中一张结果为例：
![image](https://github.com/Linfeng-Tang/VIF-Benchmark/assets/110177035/3f5e9347-844b-4141-b257-9934fc622a6b)

**Comment by Linfeng-Tang** [comment]
可能是显卡或者CUDA与Tensorflow不适配导致的。你可以看看单独跑某一个程序会不会有问题呢？

**Comment by WenhaoSong-1512** [comment]
感谢您的回答，我单独测试CSF仍存在上述图像问题，我是否应该更新tenserflow和pytorch版本

**Comment by Linfeng-Tang** [comment]
基于Tensorflow的哪些程序之前都是在低版本的CUDA 和Tensorflow上进行训练和测试的，要想成功运行的话 应该要降级

**Comment by WenhaoSong-1512** [comment]
您好，我目前使用的是CUDA 10.2，tensorflow 1.14.0，按照您提供的conda env create -f timer.yml创建的环境，仍然存在问题，您还有什么建议吗，十分感谢您的回答

**Comment by WenhaoSong-1512** [comment]
我还注意到您给出的预训练模型有三个后缀
![image](https://github.com/Linfeng-Tang/VIF-Benchmark/assets/110177035/196a02a0-f716-4de6-90f8-c907c57ed251)
而程序中导入模型为
![image](https://github.com/Linfeng-Tang/VIF-Benchmark/assets/110177035/f050d230-538d-4583-b22b-2931942cd186)
为什么是这样

**Comment by Linfeng-Tang** [comment]
Tensorflow 导入模型的格式就是这样的。

**Comment by Linfeng-Tang** [comment]
> 

你可以尝试使用CPU版的Tensorflow 看看效果是否好转

**Comment by WenhaoSong-1512** [comment]
感谢您的回答，使用cpu版本后可以了

**Comment by Wbzb** [comment]
请问在已经按timer配置好环境的基础上，怎么使用CPU版本的Tensorflow呢
已经解决了，只要修改成f.write("CUDA_VISIBLE_DEVICES=-1 即可

**Comment by nameOfjinshuai** [comment]
> 请问在已经按timer配置好环境的基础上，怎么使用CPU版本的Tensorflow呢 已经解决了，只要修改成f.write("CUDA_VISIBLE_DEVICES=-1 即可

谢谢你的回答，我也有相同的问题，已经按照你的操作解决了，再次谢谢你。

**Comment by cwl520wwh** [comment]
> 你好，我运行代码后出现了代码运行很久后中断的问题，请问可以帮助解决吗？十分感谢 0%| | 0/12 [00:00<?, ?it/s] 0%| | 0/12 [12:29<?, ?it/s] Traceback (most recent call last): File "CSF.py", line 60, in is_RGB=opts.is_RGB File "CSF.py", line 36, in main generate(ir_path, vis_path, model_path_1, model_path_2, output_path=save_path) File "/home/wenhao/projects/VIF-Benchmark/CSF/generate.py", line 56, in generate vis_feas_output = sess.run(feas, feed_dict = FEED_DICT_VIS) File "/home/wenhao/installs/conda/envs/timer/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run run_metadata_ptr) File "/home/wenhao/installs/conda/envs/timer/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1173, in _run feed_dict_tensor, options, run_metadata) File "/home/wenhao/installs/conda/envs/timer/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run run_metadata) File "/home/wenhao/installs/conda/envs/timer/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call return fn(*args) File "/home/wenhao/installs/conda/envs/timer/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn options, feed_dict, fetch_list, target_list, run_metadata) File "/home/wenhao/installs/conda/envs/timer/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun run_metadata) KeyboardInterrupt

您好，我看您是通过换一张显卡就解决一直卡着不动这个问题，我想询问下您， 您前后使用的显卡是什么呀？我现在也是卡在这块，希望得到您的回复，谢谢您！

**Comment by Linfeng-Tang** [comment]
主要的问题在于比较新的显卡和CUDA不支持Tensorflow 1.几的版本 可以考虑使用CPU来跑这些算法

**Comment by cwl520wwh** [comment]
> 主要的问题在于比较新的显卡和CUDA不支持Tensorflow 1.几的版本可以考虑使用CPU来跑这些算法

您好，我明白您的意思了。那么使用CPU显卡来跑的话，如何修改代码呢？ 是直接在All_in_One.py脚本的导包部分写入：f.write（“CUDA_VISIBLE_DEVICES=-1）就可以吗？

**Comment by li20220125** [comment]
> 您好，我换了一张显卡后成功运行，可是生成的融合图像比较糟糕，请问是什么原因？以CSF中一张结果为例： ![image](https://private-user-images.githubusercontent.com/110177035/242596704-3f5e9347-844b-4141-b257-9934fc622a6b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYzMjY2MTcsIm5iZiI6MTczNjMyNjMxNywicGF0aCI6Ii8xMTAxNzcwMzUvMjQyNTk2NzA0LTNmNWU5MzQ3LTg0NGItNDE0MS1iMjU3LTk5MzRmYzYyMmE2Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwOFQwODUxNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yM2RkNmJhZWRhYjk3YzY2MDliNjcwNWViOTNiNDNlMGJhODUzZjMwZjM4MjkwODgzMDE0ZjAyYjg4MDM4NWExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.01zh0Rk9L1e1CopDKcSFEKOP3abHZn-N976Zmle5zu8)

请问一下U2Fusion，您是出现前几张融合效果正常，后面几张融合效果很差的情况吗

**Comment by Linfeng-Tang** [comment]
用CPU试试看

li20220125 ***@***.***> 于2025年1月8日周三 16:58写道：

**Comment by li20220125** [comment]
好嘞，谢谢啦，我试一下
